name = "namma-subscription-handler"
main = "index.js"
compatibility_date = "2026-02-25"
workers_dev = false

[[routes]]
pattern = "subscribe.quoteviral.online/*"
zone_name = "quoteviral.online"

[[d1_databases]]
binding = "DB"
database_name = "namma-clicks"
database_id = "52efb6db-0563-4b97-902b-46992f807773"
